name: name-alpha / delivery
run-name: name-alpha ${{ github.event_name }} ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - "name-alpha/v*" # release
    branches:
      - main
    # paths:
    #   - "cmd/name-alpha*/**"
    #   - "internal/name-alpha/**"
    #   - "chart/*/name-alpha*/**"

permissions:
  contents: read

jobs:
  sanitize_image_tag:
    name: sanitize image tag
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads') || startsWith(github.ref, 'refs/tags/') }}
    outputs:
      image_tag: ${{ steps.sanitizing_tag.outputs.image_tag }}
      tag_prd_semver: ${{ steps.sanitizing_tag.outputs.tag_prd_semver }}
    steps:
      - name: sanitizing tag
        id: sanitizing_tag
        run: |
          image_tag=${GITHUB_SHA::7}
          tag_prd_semver="false"

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            image_tag=$(echo ${{ github.ref_name }} | cut -d'/' -f2)
            echo "valid tag: $image_tag"
            if [[ "$image_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              tag_prd_semver="true"
              echo "go to production"
            fi
          fi

          echo "tag_prd_semver=$tag_prd_semver" >> $GITHUB_OUTPUT
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: sanitize_image_tag
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const script = require('./infra/gha/release-notes.js')
            console.log(script({github, context, core, glob}))

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "Deploy efetuado com sucesso!"
