name: build and deploy
run-name: ${{ github.event_name }} ${{ github.ref_name }} by @${{ github.actor }}

permissions:
  contents: read
  deployments: read

on:
  push:
    branches:
      - 'main'

jobs:
  get-namespace:
    uses: ./.github/workflows/stncard_go_detect_namespace.yaml
    with:
      RUNS_ON: ubuntu-latest
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.get-namespace.outputs.NAMESPACES != '[]'
    needs: get-namespace
    uses: ./.github/workflows/stncard_go_deploy_stg_namespace.yaml
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        NAMESPACE: ${{ fromJson(needs.get-namespace.outputs.NAMESPACES) }}
    with:
      RUNS_ON: ubuntu-latest
      NAMESPACE: ${{ matrix.NAMESPACE }}




      