name: build and deploy
run-name: ${{ github.event_name }} ${{ github.ref_name }} by @${{ github.actor }}

permissions:
  contents: write
  deployments: read

on:
  push:
    branches:
      - 'main'

jobs:
  get-namespace:
    runs-on: ubuntu-latest
    # outputs:
    #   SHORT_TAG: ${{ steps.set_output.outputs.SHORT_TAG }}
    #   NAMESPACE: ${{ steps.set_output.outputs.NAMESPACE }}
    #   APPLICATIONS: ${{ steps.set_output.outputs.APPLICATIONS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get files changed
        id: files-changed
        uses: tj-actions/changed-files@v45
        with:
          files_ignore: |
            .github/**
            .git/**
            .vscode/**
          separator: ","

      - name: get namespace
        id: extract-namespace-path
        env:
          all_changed_files_list: ${{ steps.files-changed.outputs.all_changed_files }}
        run: |
          echo "All changed files: $all_changed_files_list"

          # split on commas
          IFS=',' read -ra FILES <<< "$all_changed_files_list"
          declare -A ns_map
          for f in "${FILES[@]}"; do
            # match internal/<ns>/... or cmd/<ns>/...
            if [[ "$f" =~ ^(internal|cmd)/([^/]+)/ ]]; then
              ns="${BASH_REMATCH[2]}"
              ns_map[$ns]=1
            fi
          done
          # build JSON array
          mapfile -t uniq_ns < <(printf "%s\n" "${!ns_map[@]}" | sort)
          NAMESPACES=$(printf '[%s]' "$(printf '"%s",' "${uniq_ns[@]}" | sed 's/,$//')")
          echo "NAMESPACES=$NAMESPACES" >> $GITHUB_OUTPUT
          echo "NAMESPACES=$NAMESPACES"
  
  deploy:
    needs: get-namespace
    uses: ./.github/workflows/stncard_go_deploy_stg_namespace.yaml
    strategy:
      fail-fast: true
      matrix:
        NAMESPACE: ${{ fromJson(needs.get-namespace.outputs.NAMESPACES) }}
    with:
      RUNS_ON: ubuntu-latest
      NAMESPACE: ${{ matrix.NAMESPACE }}




      