name: build
run-name: ${{ github.event_name }} ${{ github.event.pull_request.number }} to ${{ github.base_ref }} by @${{ github.actor }} - ${{ github.event.pull_request.title }}

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "cmd/**/*.go"
      - "internal/**/*.go"
      - "go.mod"
      - "go.sum"
jobs:
  get-namespace:
    uses: ./.github/workflows/stncard_go_detect_namespace.yaml
    with:
      RUNS_ON: ubuntu-latest
    secrets: inherit
  
  ci:
    name: Go CI
    uses: ./.github/workflows/stncard_go_ci_v1.yaml
    needs: get-namespace
    strategy:
      fail-fast: true
      matrix:
        NAMESPACE: ${{ fromJson(needs.get-namespace.outputs.NAMESPACES) }}
    with:
      NAMESPACE: ${{ matrix.NAMESPACE }}
      RUNS_ON: ubuntu-latest
    secrets: inherit
