name: build and deploy
run-name: ${{ inputs.namespace }} ${{ github.event_name }} ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Namespace'
        required: true
        type: choice
        options:
          - namespace
          - beta
          - gamma
          - delta
          - epsilon
      bumpType:
        description: 'Tipo de versão'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - rc
        default: minor
      descricao_da_mudanca:
        description: 'Descrição detalhada da mudança que será realizada'
        required: true
        type: string
      objetivo_da_mudanca:
        description: 'Objetivo e motivo da mudança'
        required: true
        type: string
      plano_de_rollback:
        description: 'Plano de rollback em caso de problemas'
        required: true
        type: string
      plano_de_teste:
        description: 'Plano de testes para validar a mudança'
        required: true
        type: string
      link_do_card_no_jira:
        description: 'opcional] Link do card no Jira'
        required: false
        type: string
        default: ''
      id_do_incidente_opsgenie:
        description: 'opcional] ID do incidente no Opsgenie'
        required: false
        type: string
        default: ''

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set_output.outputs.VERSION }}
      PREVIOUS_TAG: ${{ steps.set_output.outputs.PREVIOUS_TAG }}
      HOTFIXES: ${{ steps.set_output.outputs.HOTFIXES }}
      TAG_PRD_SEMVER: ${{ steps.set_output.outputs.TAG_PRD_SEMVER }}
      TAG: ${{ steps.set_output.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: find tag
        id: find_tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const script = require('./infra/gha/generate-tag.js')
            return await script.generateTag(
              {core, context},
              core.getInput('namespace'),
              core.getInput('bumpType'),
            )

      - name: set-output
        id: set_output
        env:
          RESULT: ${{ steps.find_tag.outputs.result }}
        run: |
          echo "PREVIOUS_TAG=$(echo $RESULT | jq -r '.previousTag')" >> $GITHUB_OUTPUT
          echo "HOTFIXES=$(echo $RESULT | jq -r '.hotfixes')" >> $GITHUB_OUTPUT
          echo "TAG_PRD_SEMVER=$(echo $RESULT | jq -r '.tagPRD')" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo $RESULT | jq -r '.version')" >> $GITHUB_OUTPUT
          echo "TAG=$(echo $RESULT | jq -r '.tag')" >> $GITHUB_OUTPUT

          # Debug
          echo "$RESULT"
          echo "PREVIOUS_TAG=$(echo "$RESULT" | jq -r '.previousTag')"
          echo "HOTFIXES=$(echo "$RESULT" | jq -r '.hotfixes')"
          echo "TAG_PRD_SEMVER=$(echo "$RESULT" | jq -r '.tagPRD')"
          echo "VERSION=$(echo "$RESULT" | jq -r '.version')"
          echo "TAG=$(echo "$RESULT" | jq -r '.tag')"

  release-notes:
    # runs-on: small-runner
    runs-on: ubuntu-latest
    needs: [generate-tag]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/github-script@v7
        name: create release notes
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const script = require('./infra/gha/release-notes.js')
            await script(
              {github, context, core, glob},
              "${{ needs.prepare-tag.outputs.PREVIOUS_TAG }}",
              "${{ github.ref_name }}",
              "${{ inputs.descricao_da_mudanca }}",
              "${{ inputs.objetivo_da_mudanca }}",
              "${{ inputs.plano_de_rollback }}",
              "${{ inputs.plano_de_teste }}",
              "${{ inputs.link_do_card_no_jira }}",
              "${{ inputs.id_do_incidente_opsgenie }}",
              "${{ needs.prepare-tag.outputs.HOTFIXES }}",
            )