name: build and deploy
run-name: ${{ github.event_name }} ${{ github.ref_name }} by @${{ github.actor }}

permissions:
  contents: write
  deployments: read

on:
  push:
    branches:
      - 'main'

jobs:
  detect-namespace:
    runs-on: ubuntu-latest
    # outputs:
    #   SHORT_TAG: ${{ steps.set_output.outputs.SHORT_TAG }}
    #   NAMESPACE: ${{ steps.set_output.outputs.NAMESPACE }}
    #   APPLICATIONS: ${{ steps.set_output.outputs.APPLICATIONS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get files changed
        id: files-changed
        uses: tj-actions/changed-files@v45
        with:
          files_ignore: |
            .github/**
            .git/**
            .vscode/**
          separator: ","

      - name: Extract Namespace by Path Changes
        id: extract-namespace-path
        env:
          all_changed_files_list: ${{ steps.files-changed.outputs.all_changed_files }}
        run: |
          echo "All changed files: $all_changed_files_list"







      