name: Release / New
run-name: ${{ github.event_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace"
        required: true
        default: ""
      minor:
        description: "Minor (recommended)"
        required: false
        default: true
        type: boolean
      hotfix:
        description: "Hotfix (non main branch)"
        required: false
        default: false
        type: boolean
      rc:
        description: "Release Candidate"
        required: false
        default: false
        type: boolean
      major:
        description: "Breaking Change"
        required: false
        default: false
        type: boolean
      tag:
        description: "Tag (ex.: vX.Y.Z)"
        required: false
        default: ""
        type: string

jobs:
  generate-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: validate inputs
        run: |
          if [ -z "${{ github.event.inputs.namespace }}" ]; then
              echo "::error::namespace is required"
              exit 1
          fi

          count=0

          if [ "${{ github.event.inputs.major }}" = "true" ]; then count=$((count + 1)); fi
          if [ "${{ github.event.inputs.minor }}" = "true" ]; then count=$((count + 1)); fi
          if [ "${{ github.event.inputs.hotfix }}" = "true" ]; then count=$((count + 1)); fi
          if [ "${{ github.event.inputs.rc }}" = "true" ]; then count=$((count + 1)); fi
          if [ -n "${{ github.event.inputs.tag }}" ]; then count=$((count + 1)); fi

          if [ $count -ne 1 ]; then
              echo "::error::Only one of minor, hotfix, rc, or tag must be specified"
              exit 1
          fi

          if [ ! -d "./internal/${{ github.event.inputs.namespace }}" ]; then
              echo "::error::Invalid namespace: ${{ github.event.inputs.namespace }} does not exist. Valid namespaces are: $(ls ./internal | paste -sd ';' -)"
              exit 1
          fi

          echo "${{ github.event.inputs.tag }}"
          if [ -n "${{ github.event.inputs.tag }}" ]; then
              echo "entrei aqui!"
              if ! echo "${{ github.event.inputs.tag }}" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$'; then
                  echo "::error::Invalid tag format: ${{ github.event.inputs.tag }}. Must be a valid semver (e.g., v0.0.0-0)"
                  exit 1
              fi

              if git rev-parse "${{ github.event.inputs.namespace }}/${{ github.event.inputs.tag }}" >/dev/null 2>&1; then
                  echo "::error::Tag already exists: ${{ github.event.inputs.tag }} to namespace ${{ github.event.inputs.namespace }} "
                  exit 1
              fi
          fi

      - name: find tag
        id: find_tag
        uses: actions/github-script@v7
        if: ${{ github.event.inputs.tag == '' }}
        with:
          github-token: ${{ secrets.TOKEN }}
          result-encoding: string
          script: |
            const script = require('./infra/gha/generate-tag.js')
            return await script(
            {core},
              "${{ github.event.inputs.namespace }}", 
              ${{ github.event.inputs.major }}, 
              ${{ github.event.inputs.minor }}, 
              ${{ github.event.inputs.hotfix }},  
              ${{ github.event.inputs.rc }}
            )

      - name: create tag - auto generated
        id: create_tag_auto_generated
        uses: actions/github-script@v7
        if: ${{ github.event.inputs.tag == '' }}
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const tagName = "${{ steps.find_tag.outputs.result }}";
            const message = `auto-generated tag: ${tagName}`;
            const commitSha = context.sha;
            const taggerName = process.env.GITHUB_ACTOR;
            const taggerEmail = `${taggerName}@users.noreply.github.com`;
            
            // Criar a tag anotada com informações do executor
            const { data: ghTag } = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tagName,
              message: message,
              object: commitSha,
              type: "commit",
              tagger: {
                name: taggerName,
                email: taggerEmail,
                date: new Date().toISOString(),
              }
            });

            // Criar a referência apontando para a tag anotada
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: ghTag.sha
            });

            core.notice(`Tag created (auto-generated): ${tagName}`);
      
      - name: create tag - self defined
        id: create_tag_self_defined
        uses: actions/github-script@v7
        if: ${{ github.event.inputs.tag != '' }}
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const tag = "${{ github.event.inputs.tag}}";
            const namespace = "${{ github.event.inputs.namespace }}";
            const tagName = `${namespace}/${tag}`;
            const message = `self-defined tag: ${tagName}`;
            const commitSha = context.sha;
            const taggerName = process.env.GITHUB_ACTOR;
            const taggerEmail = `${taggerName}@users.noreply.github.com`;
            
            // Criar a tag anotada com informações do executor
            const { data: ghTag } = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tagName,
              message: message,
              object: commitSha,
              type: "commit",
              tagger: {
                name: taggerName,
                email: taggerEmail,
                date: new Date().toISOString(),
              }
            });

            // Criar a referência apontando para a tag anotada
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: ghTag.sha
            });

            core.notice(`Tag created (self-defined): ${tagName}`);
      