name: Release / New
run-name: ${{ github.event_name }} by @${{ github.actor }}

on:
    workflow_dispatch:
        inputs:
            namespace:
                description: 'Namespace'
                required: true
                default: ''
            minor:
                description: 'Minor'
                required: false
                default: true
                type: boolean
            hotfix:
                description: 'Hotfix'
                required: false
                default: false
                type: boolean
            rc:
                description: 'Release Candidate'
                required: false
                default: false
                type: boolean
            major:
                description: 'Breaking Change'
                required: false
                default: false
                type: boolean
            tag:
                description: 'Tag'
                required: false
                default: ''
                type: string

jobs:
    generate-tags:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: validate inputs
              run: |
                    if [ -z "${{ github.event.inputs.namespace }}" ]; then
                        echo "::error::namespace is required"
                        exit 1
                    fi

                    count=0

                    if [ "${{ github.event.inputs.major }}" = "true" ]; then count=$((count + 1)); fi
                    if [ "${{ github.event.inputs.minor }}" = "true" ]; then count=$((count + 1)); fi
                    if [ "${{ github.event.inputs.hotfix }}" = "true" ]; then count=$((count + 1)); fi
                    if [ "${{ github.event.inputs.rc }}" = "true" ]; then count=$((count + 1)); fi
                    if [ -n "${{ github.event.inputs.tag }}" ]; then count=$((count + 1)); fi

                    if [ $count -ne 1 ]; then
                        echo "::error::Only one of minor, hotfix, rc, or tag must be specified"
                        exit 1
                    fi

                    if [ ! -d "./internal/${{ github.event.inputs.namespace }}" ]; then
                        echo "::error::Invalid namespace: ${{ github.event.inputs.namespace }} does not exist"
                        exit 1
                    fi

                    if [ -n "${{ github.event.inputs.tag }}" ]; then
                        if ! echo "${{ github.event.inputs.tag }}" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$'; then
                            echo "::error::Invalid tag format: ${{ github.event.inputs.tag }}. Must be a valid semver (e.g., v0.0.0-0)"
                            exit 1
                        fi

                        if git rev-parse "${{ github.event.inputs.namespace }}/${{ github.event.inputs.tag }}" >/dev/null 2>&1; then
                            echo "::error::Tag already exists: ${{ github.event.inputs.tag }} to namespace ${{ github.event.inputs.namespace }} "
                            exit 1
                        fi
                    fi

            
            - name: generate
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.TOKEN }}
                  script: |
                    const script = require('./infra/gha/generate-tag.js')
                    console.log(await script(
                      {github, context, core}, 
                      "${{ github.event.inputs.namespace }}", 
                      ${{ github.event.inputs.major }}, 
                      ${{ github.event.inputs.minor }}, 
                      ${{ github.event.inputs.hotfix }},  
                      ${{ github.event.inputs.rc }}, 
                      "${{ github.event.inputs.tag }}"
                    ))
          

                    