name: go ci v1
run-name: ${{ github.event_name }} ${{ github.event.pull_request.number }} to ${{ github.base_ref }} by @${{ github.actor }} - ${{ github.event.pull_request.title }}

concurrency:
  group: ${{inputs.NAMESPACE}}-${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      NAMESPACE:
        description: Name of the namespace to build.
        required: true
        type: string
      GOMOD_PATH:
        description: Go version to be used.
        required: false
        type: string
        default: "go.mod"
      RUNS_ON:
        description: Choose runner type.
        required: false
        type: string
        default: small-runner
      GH_APP_ID:
        required: false
        type: number
        default: 892349
        description: 'Github App ID'
    secrets:
      GH_APP_ST_BANKING_CARD_PEM:
        description: PEM from GIthub Action Key.
        required: false

jobs:
  compile:
    name: Go Compile
    uses: ./.github/workflows/stncard_go_build_go.yaml
    with:
      NAMESPACE: ${{ inputs.NAMESPACE }}
    secrets: inherit

  build:
    name: Build
    needs: [compile]
    uses: stone-payments/platform-k8s-github-actions/.github/workflows/karavela_build.yml@main
    with:
      REGISTRY_NAME: bank-${{ inputs.NAMESPACE }}}}
      IMAGE_TAG: ${{ github.sha }}
      ARTIFACT_NAME: ${{ needs.compile.outputs.artifact_name }}
      ARTIFACT_PATH: ${{ needs.compile.outputs.artifact_dir }}
      PUSH_IMAGE: false
    secrets: inherit

  tests:
    name: tests
    runs-on: ${{ inputs.RUNS_ON }}
    env:
      GITHUB_SHA: ${{ github.sha }}
      __NS__: ${{ inputs.NAMESPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/create-github-app-token@v1
        id: app-token-dlpco
        with:
          app-id: ${{ inputs.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_ST_BANKING_CARD_PEM }}
          owner: dlpco

      - uses: actions/create-github-app-token@v1
        id: app-token-stone-payments
        with:
          app-id: ${{ inputs.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_ST_BANKING_CARD_PEM }}
          owner: stone-payments

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.GOMOD_PATH }}

      - name: prepare infra
        env:
          GO111MODULES: on
          GOPRIVATE: github.com/dlpco/*,github.com/stone-payments/*
          APP_TOKEN_DLPCO: ${{ steps.app-token-dlpco.outputs.token  }}
          APP_TOKEN_STONE_PAYMENTS: ${{ steps.app-token-stone-payments.outputs.token  }}
        run: |
          git config --global url."https://x-access-token:$APP_TOKEN_STONE_PAYMENTS@github.com/stone-payments/".insteadOf "https://github.com/stone-payments/"
          git config --global url."https://x-access-token:$APP_TOKEN_DLPCO@github.com/dlpco/".insteadOf "https://github.com/dlpco/"

          make install-ci-tools
          go mod download

      - name: go.mod
        run: |
          go mod tidy
          git diff --exit-code

      - name: generate
        run: |
          make generate-lint
          git diff --exit-code

      - name: test
        run: |
          make test-ci

  vulnerability:
    name: vulnerability
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/create-github-app-token@v1
        id: app-token-dlpco
        with:
          app-id: ${{ inputs.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_ST_BANKING_CARD_PEM }}
          owner: dlpco

      - uses: actions/create-github-app-token@v1
        id: app-token-stone-payments
        with:
          app-id: ${{ inputs.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_ST_BANKING_CARD_PEM }}
          owner: stone-payments

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.GOMOD_PATH }}

      - name: prepare infra
        env:
          GO111MODULES: on
          GOPRIVATE: github.com/dlpco/*,github.com/stone-payments/*
          APP_TOKEN_DLPCO: ${{ steps.app-token-dlpco.outputs.token  }}
          APP_TOKEN_STONE_PAYMENTS: ${{ steps.app-token-stone-payments.outputs.token  }}
        run: |
          git config --global url."https://x-access-token:$APP_TOKEN_STONE_PAYMENTS@github.com/stone-payments/".insteadOf "https://github.com/stone-payments/"
          git config --global url."https://x-access-token:$APP_TOKEN_DLPCO@github.com/dlpco/".insteadOf "https://github.com/dlpco/"

      - id: govulncheck
        uses: golang/govulncheck-action@v1.0.4
        with:
          repo-checkout: false
          go-version-file: go.mod
          go-package: ./internal/${{ inputs.NAMESPACE }}/... ./cmd/${{ inputs.NAMESPACE }}/...

  lint:
    name: lint
    runs-on: ${{ inputs.RUNS_ON }}
    env:
      GITHUB_SHA: ${{ github.sha }}
      __NS__: ${{ inputs.NAMESPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/create-github-app-token@v1
        id: app-token-dlpco
        with:
          app-id: ${{ inputs.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_ST_BANKING_CARD_PEM }}
          owner: dlpco

      - uses: actions/create-github-app-token@v1
        id: app-token-stone-payments
        with:
          app-id: ${{ inputs.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_ST_BANKING_CARD_PEM }}
          owner: stone-payments

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.GOMOD_PATH }}

      - name: prepare infra
        env:
          GO111MODULES: on
          GOPRIVATE: github.com/dlpco/*,github.com/stone-payments/*
          APP_TOKEN_DLPCO: ${{ steps.app-token-dlpco.outputs.token  }}
          APP_TOKEN_STONE_PAYMENTS: ${{ steps.app-token-stone-payments.outputs.token  }}
        run: |
          git config --global url."https://x-access-token:$APP_TOKEN_STONE_PAYMENTS@github.com/stone-payments/".insteadOf "https://github.com/stone-payments/"
          git config --global url."https://x-access-token:$APP_TOKEN_DLPCO@github.com/dlpco/".insteadOf "https://github.com/dlpco/"

      - name: go.mod
        run: |
          go mod tidy
          git diff --exit-code

      - name: golangci-lint-internal
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./internal/${{ inputs.NAMESPACE }}

      - name: golangci-lint-cmd
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: v2.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./cmd/${{ inputs.NAMESPACE }}