name: Namespace

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      NAMESPACE:
        description: "The namespace to be detected"
        type: string
        required: true
      APPLICATIONS:
        description: "The applications associated to namespace, separated by comma"
        type: string
        required: true
      RUNS_ON:
        description: Choose runner type.
        required: false
        type: string
        default: small-runner

jobs:
  namespace:
    name: Summary
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: show info
        env:
          NAMESPACE: ${{ inputs.NAMESPACE }}
          APPLICATIONS: ${{ inputs.APPLICATIONS }}
        run: |
          echo $NAMESPACE
          echo $APPLICATIONS
          echo "## :satellite: Namespaces detectados: :satellite:" >> $GITHUB_STEP_SUMMARY

          echo "### Namespace: :dart: $NAMESPACE" >> $GITHUB_STEP_SUMMARY
          echo "[Namespace no ArgoCD](https://argocd.stone.tech/applications?search=$NAMESPACE)" >> $GITHUB_STEP_SUMMARY
          echo "#### Applications:" >> $GITHUB_STEP_SUMMARY

          for app in $(echo "$APPLICATIONS" | jq -r '.[]'); do
            echo "$app"
            echo "- :crown: *[$app](https://argocd.stone.tech/applications?search=$app)*" >> $GITHUB_STEP_SUMMARY
          done

